server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/space/user/auth/**
              filters:
                - RewritePath=/space/user/auth/(?<segment>.*), /user/auth/${segment}

            - id: auth-swagger
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/space/user/auth/v3/api-docs/**,/space/user/auth/swagger-ui/**,/space/user/auth/swagger-ui.html
              filters:
                  - RewritePath=/space/user/auth/(?<segment>.*), /user/auth/${segment}

            - id: users-service
              uri: lb://USERS-SERVICE
              predicates:
                - Path=/space/users/**
              filters:
                - RewritePath=/space/users/(?<segment>.*), /${segment}

            - id: users-swagger
              uri: lb://USERS-SERVICE
              predicates:
                - Path=/space/users/v3/api-docs/**,/space/users/swagger-ui/**,/space/users/swagger-ui.html
              filters:
                  - RewritePath=/space/users/(?<segment>.*), /${segment}

            - id: media
              uri: lb://MEDIA-CONTENT
              predicates:
                - Path=/space/media/**
              filters:
                - RewritePath=/space/media/(?<segment>.*), /${segment}

            - id: media-swagger
              uri: lb://MEDIA-CONTENT
              predicates:
                - Path=/space/media/v3/api-docs/**,/space/media/swagger-ui/**,/space/media/swagger-ui.html
              filters:
                - RewritePath=/space/media/(?<segment>.*), /${segment}

            - id: preferences
              uri: lb://PREFERENCE-SERVICE
              predicates:
                - Path=/preferences/**

            - id: preferences-swagger
              uri: lb://PREFERENCE-SERVICE
              predicates:
                - Path=/preferences/v3/api-docs/**,/preferences/swagger-ui/**,/preferences/swagger-ui.html
              filters:
                - RewritePath=/preferences/(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: api-gateway

jwt:
  secret: EtWBmqNcSkSZT5U1BWVwYTJaGyZz+buud4N0y1Ef4+PD+ofgl69e1a/d1SrrzyUTC5tYx714GyjdvATH+cYZy3lm2bbt9zwxVPTLzoJ0zhmc3qP9eyDXXP4sqyFL9ADhW72FCBuxXKwE22M3by3oIhOBsQ3XxeopZrwOldu+jx5HA4UJBLfOnh6n8OAnJqTomeJTH/mEX34koeP6j+EO92r3YA1BMggD6qs2xceFBOh2y4pds+8rhU1qree10oXg1D4QvWFoQKJ15kUZRbKkgtPskFSo3Rbrc+6sONyaWzBUOFhhE5ZmhhEzEGAw6Rac67JDYc1YzvIcskry1EO7mMtDeq9JUsUGNFm2TjXf+6E=

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.transport: DEBUG

springdoc:
  swagger-ui:
    urls:
      - name: users-service
        url: /space/users/v3/api-docs
      - name: auth-service
        url: /space/user/auth/v3/api-docs
      - name: media-content
        url: /space/media/v3/api-docs
      - name: preferences
        url: /preferences/v3/api-docs
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true
